### ISSUE TITLE
Plugin possible compatibility issues with new Dalamud

### ISSUE THREAD

**Issue by Grammernatzi** [Grammernatzi/XIVComboPluginExpandedest#10]
Title. Will be working on it during the week, I need to update the whole backbone of the plugin to be up-to-date with Daemitus's code.

**Comment by Iaotle** [comment]
Sweet dude, I'll let you know if I run into anything.

**Comment by Krazzeekane** [comment]
Heya, I just updated to the latest version via the new plugin installer, and I am not seeing the icons updating for warrior for any of the combos: Storm's Eye, Storm's Path, and Mythril Tempest. 

Mechanically it functions properly and does the combos in the right order when pressing the single button 3 times, but the icon of those buttons aren't changing/updating for some reason, and I notice the option to toggle the icon change is now gone, does this mean this functionality has been removed?

It's not the biggest issue, but I liked the icon updating so if this is something that is fixable that would be excellent!

**Comment by Krazzeekane** [comment]
Oh my mistake, I never knew that toggling the class would fix icon issues, I swapped to a different class then back and it updates properly now! Appreciate the tip, if it was posted somewhere and I missed it I apologize :)

**Comment by Noshei** [comment]
/pcombo doesn't appear to be working, but might be because I had xivcombo enabled at first.

**Comment by Grammernatzi** [comment]
Definitely restart your game after turning off the original plugin; if it's not fixed by that, then you might need to clean reinstall or the like

**Comment by Noshei** [comment]
restarting the game resolved it.  Everything else looks good so far.  Thanks for getting this working again so fast, this plugin makes the game so much more enjoyable for me.

**Comment by Noshei** [comment]
also, was it intended to include the "secret" combos?

**Comment by Grammernatzi** [comment]
It is part of Daemitus's original fork, so I was allowed to do so. Basically, it's okay for me to maintain parity with his fork, because there's no reason for mine to lack features his has. I already discussed it with the Dalamud moderation in the past. If he removes features, though, I will too, as part of that.
