### ISSUE TITLE
Mudra to Ninjitsu suggestion

### ISSUE THREAD

**Issue by AwesomeJames2120** [Grammernatzi/XIVComboPluginExpandedest#15]
Heya, i just had a semi decent idea for a new combo for ninja

Since each mudra can only be used once or else it fails, what if you made it so that used mudras automatically swap with ninjitsu? That way one can just press their last mudra button twice to execute a combo.

**Comment by Grammernatzi** [comment]
Sadly reading mudras is broken at the moment, so while I can add this in the future, I will have to wait on that.

**Comment by Grammernatzi** [comment]
For now I'll close this, when it becomes possible I'll try to add it.
