### ISSUE TITLE
Warrior Gauge Overcap Feature not working?

### ISSUE THREAD

**Issue by RedReverend** [Grammernatzi/XIVComboPluginExpandedest#16]
Hi.
Testing out the warrior combos and the Warrior Gauge Overcap feature seems to only swap Mythril Tempest for Decimate, but neither of the single target combos for Fell Cleave.

**Comment by Zeemgeem** [comment]
Hey, this is old and all but I think the description should be updated to reflect that it only affects AOE, shouldn't it?

**Comment by Grammernatzi** [comment]
Fair enough, I should've done that earlier.
