### ISSUE TITLE
DRK Quietus/Stalwart Soul overcap feature not working

### ISSUE THREAD

**Issue by Iaotle** [Grammernatzi/XIVComboPluginExpandedest#17]
Stalwart Soul doesn't get replaced with Quietus, allowing overcap.

**Comment by Grammernatzi** [comment]
I will look at this, it might've gotten changed with the upgrade to the new Dalamud version.

**Comment by Grammernatzi** [comment]
It should be fixed now but I haven't tested it since I'm not at my desktop PC, I put the logic back in for it, it was missing.
