### ISSUE TITLE
Suggestion: DRK Souleater/Bloodspiller overcap feature

### ISSUE THREAD

**Issue by Iaotle** [Grammernatzi/XIVComboPluginExpandedest#18]
Title pretty much says it. Replace Souleater with Bloodspiller if it would cause you to overcap.

**Comment by Grammernatzi** [comment]
This one I actually had to remove before, sorry. The moderators did not like it because it simplified your single-target rotation too much. They were okay with it in AoE because that was just for trash mobs in dungeons, pretty much.
