### ISSUE TITLE
Suggestion: Change Aeolian Combo Buttons to Mudras during Ten Chi Jin. 

### ISSUE THREAD

**Issue by RandomSuggestions** [Grammernatzi/XIVComboPluginExpandedest#19]
I know there's a lot of Ninja features already, but it'd be really nice if while under the status of the Ten Chi Jin buff, that Spinning Edge, Gust Slash and Aeolian Edge also transformed into the Ten/Chi/Jin buttons respectively for that six second buff duration.

**Comment by Grammernatzi** [comment]
It's an interesting idea, but it wouldn't really save any buttons and I have a lot on my plate for Endwalker to add; so, it'd have to be a low priority, I apologize. If you or someone else manages to add it, though, and submits it in a Pull Request, I wouldn't mind adding it, I already have just so much planned to add for EW as it is.

**Comment by Grammernatzi** [comment]
At the moment I will close this, maybe'll look at it later
