### ISSUE TITLE
your code is trash and so are you :p

### ISSUE THREAD

**Issue by daemitus** [Grammernatzi/XIVComboPluginExpandedest#2]
https://github.com/Grammernatzi/XIVComboPluginExpandedest/blob/fa92de8d4921f58d303f723177afd3e5644bb5cc/XIVComboPlugin/IconReplacer.cs#L662

```               
 if (actionID == SAM.TsubameGaeshi)
                {
                    var gauge = GetJobGauge<SAMGauge>();
                    if (level >= SAM.Levels.TsubameGaeshi && gauge.Sen == Sen.NONE)
                        return GetIconHook.Original(self, SAM.TsubameGaeshi);
                    else
                        return GetIconHook.Original(self, SAM.Iaijutsu);
                }
```

**Comment by daemitus** [comment]
Gently trolling. Had a request for Tsubame come up, then noticed you did some of the work already. Rolled your Shoha feat in too.

**Comment by Grammernatzi** [comment]
This is a good point, I'm still inexperienced with Dalamud and didn't know you could do that. That said, I could probably work this in with what I have, as well as add the code to prevent Kaeshi: Higanbana from happening so you don't accidentally do it and waste Tsubame if you're mindlessly mashing the button.

**Comment by daemitus** [comment]
If you actually goto the icon replacer function, its a bunch of if statements for if action ID do this other thing. so yeah, you can totally repurpose it to do the original chain.

**Comment by Grammernatzi** [comment]
I'll look into repurposing stuff when I get on

**Comment by daemitus** [comment]
save off the geticonhook.original, if == higanbana, return an action that cant be used maybe.
