### ISSUE TITLE
SMN: Proc based changes

### ISSUE THREAD

**Issue by WesBosch** [Grammernatzi/XIVComboPluginExpandedest#26]
I think it may be valid to replace Ruin and Outburst with their elementally aspected counterparts (gemshine and precious brilliance, respectively) when those abilities are avaliable.
I believe these are tied to the "primal-name's favor" statuses, but I'm not really sure how to track those to use as variables. Does anyone have any clues?

Ideally, I'm looking for:
Ruin -> Gemshine (when avaliable)
Outburst -> Precious Brilliance (when avaliable)

Unrelated to the above, but possibly also: 
Ruin -> Ruin IV (When Further Ruin is avaliable)

I understand this request may be controversial since it reduces the hotbar by a lot, so I'm willing to fork and build my own if necessary, But I'm just not sure how to define the new elemental procs.

**Comment by F-a-y-t-h** [comment]
I say you would be better off having Gemstone and Precious Brilliance act as Ruin when not aligned; as ruby has extended cast times, you may need the option to use Ruin/Ruin4 for slide casting.

**Comment by WesBosch** [comment]
That's a really good point, I hadn't thought of the cast times

**Comment by Grammernatzi** [comment]
Added in newest version, but I added a disclaimer for the single-target versions, since they can mess up your movement options.
