### ISSUE TITLE
BRD: Blast Arrow and Apex Arrow

### ISSUE THREAD

**Issue by dotsugiyoll** [Grammernatzi/XIVComboPluginExpandedest#27]
When the "Turn LB/BS into Apex Arrow" feature is turned off, they will both turn into Blast Arrow after Apex Arrow is used. There are a decent few situations where launching Apex a little early is now useful so I generally play with this function turned off. However, doing so still causes BS to turn into Blast Arrow which means I am unable to hold Blast Arrow for a few GCDs if I need to. It probably makes sense that if the "Turn LB/BS into Apex Arrow" feature is turned off then BS should not turn into BA after AA has been used.

**Comment by Grammernatzi** [comment]
I will fix this, I haven't been able to test it on Bard so thank you for letting me know, I will update it ASAP when I get on the computer. However, does using another GCD while Blast Arrow is available cancel it? This is something I'd wish to know; I will still fix it regardless, though.

**Comment by Grammernatzi** [comment]
Fixed with latest version
