### ISSUE TITLE
Suggestion:  SAM Shinten > Shoha > Senei combo

### ISSUE THREAD

**Issue by morodrim** [Grammernatzi/XIVComboPluginExpandedest#29]
I really like the Shinten > Shoha combo option.  I was wondering if it were possible to have Shinten turn into Senei when Senei is off cooldown? It would take priority over Shoha, so something like (forgive my shoddy attempt at code)...

`if(Senei.IsReady)
{
    return Senei
} 
else
{
    if(Meditation >= 3)
    {
        return Shotha
     }
    else
    {
        return Shinten
    }
}`

Naturally the same would be done for Kyuten > Shoha II > Guren

**Comment by Grammernatzi** [comment]
Sure, I'll take a look at it. Since they have the same gauge cost now, this makes sense.

**Comment by Grammernatzi** [comment]
Added, pushing in next version.
