### ISSUE TITLE
SMN: Change "Gemshine" into "Astral Flow" when Bahamut/Phoenix is out.

### ISSUE THREAD

**Issue by Megasder** [Grammernatzi/XIVComboPluginExpandedest#30]
Since there is a option to change the summon bahamut/phoenix into enkindle, and another one that changes gemshine with enkindle when bahamut/phoenix is out, so now there are 2 different buttons that do the same in the situation that these summons are out, so if it can be done, make an option (That will conflict with Shiny Enkindle Feature) that changes Gemshine with Astral Flow only when these summons are out. :)

**Comment by Grammernatzi** [comment]
Added, didn't have to make them conflicting, as Enkindle will simply take priority when it is off-cooldown if you have both enabled.
