### ISSUE TITLE
[MCH] Spread Shot Heat

### ISSUE THREAD

**Issue by MarkusWo** [Grammernatzi/XIVComboPluginExpandedest#32]
If you use the Spread Shot Heat feature on MCH, it doesn't replace Scattergun with Auto Crossbow, as you would want since Scattergun replaces Spread Shot with the L82 trait.

**Comment by Grammernatzi** [comment]
This is an issue with detecting skills; it will work if you drag spread shot to your bar and have it auto-upgrade to Scattershot. I'll add the ID real quick, but that works until it's updated.

**Comment by Grammernatzi** [comment]
Fixed

**Comment by MarkusWo** [comment]
Thank You! And Thank You in general for the plugin, I love it. Some classes I wouldn't want to play without it.
