### ISSUE TITLE
Suggestion for Tanks (and maybe Physical Ranged DPS) Role Skills that stun and interrupt.

### ISSUE THREAD

**Issue by Megasder** [Grammernatzi/XIVComboPluginExpandedest#33]
I dont know if its possible but I dont lose anything by asking so here we go.

What I sugesting is to change the role skill that stuns for the skill that interrupt if the enemy that you have targeted is using a skill that can be interrupted.

So basically, you are a tank and the enemy you are targeting is charging a skill that can be interrupted, instead of wasting your stun use the skill that is basically only made for interrupting, "Interject", and if its in cooldown or the targeted enemy is not using a interumpable skill ,use the stun skill, "Low blow".

That is why I said maybe for ranged dps, because they dont have any stun skill, however you can change "Foot Graze" or "Leg Graze" 
into "Head Graze", they dont stun but still it will remove a keybind.

Everything said, I dont know if you can check if a enemy is using a skill that can be interrumped, so if you cant then there is nothing that we can do about it, delete this and thats it XD

**Comment by Grammernatzi** [comment]
There actually is a function for checking if you can interrupt an enemy, surprisingly. So, I'll give it a look, and test it out.

**Comment by Grammernatzi** [comment]
I added this but I can't test it because of queues, I will push the update after I have tested it.

**Comment by Grammernatzi** [comment]
Now added
