### ISSUE TITLE
Suggestion: Dragoon’s Jump + Mirage Dive combo when synced / under lvl 74

### ISSUE THREAD

**Issue by Rileytaugor** [Grammernatzi/XIVComboPluginExpandedest#34]
Hey, Would it be possible to change  the **High Jump + Mirage Dive combo** to **Jump + Mirage Dive combo** when we are under lvl 74 or synced?

**Comment by Grammernatzi** [comment]
Shouldn't it already be doing this?

**Comment by Rileytaugor** [comment]
Oh, it does. I had it set up incorrectly. Sorry about that. Thank zou

po 13. 12. 2021 v 21:50 odesílatel Adam ***@***.***> napsal:
