### ISSUE TITLE
Monk AoE Combo Issue

### ISSUE THREAD

**Issue by FFXIVWytes** [Grammernatzi/XIVComboPluginExpandedest#35]
Hi there,

I just noticed that the MNK AoE combo toggle doesn't seem to be updating any of the actions in the chain. Arm of the destroyer is the base aoe action (no form required) so that's what i've put on my bars and i've got both the aoe + aoe balance functions (this doesn't update for masterful blitz either) toggled but when I use arm it just gives the form but doesn't proceed to four point fury. If i put rockbreaker on my bars it doesn't change either.

Thanks for your time.

**Comment by geramaia** [comment]
Same here. The MNK AoE combo doesn't seem to be working. None of the actions are changing no matter which aoe combo i put onto my bar.

**Comment by Grammernatzi** [comment]
Rockbreaker is changing for me. Arm/Shadow of the Destroyer is not supposed to change, only Rockbreaker and Four-Point Fury (it even says this in the description). It may be a Dalamud issue, I'm not sure. Someone else was having weird issues with SMN AoE as well on Daemitus' fork.

**Comment by FFXIVWytes** [comment]
Can give the testing fork a go. How do I add that? A different repo?

**Comment by Grammernatzi** [comment]
Dalamud has its own testing branch that you can enable via config, or in-game (you have to restart, though). [Here.](https://goatcorp.github.io/faq/dalamud_troubleshooting.html#q-how-do-i-turn-dalamud-staging-on-or-off) I only recommend using it if you have to, though, of course.

**Comment by Megasder** [comment]
Before it didnt work but after the newest update a few minutes ago it works again (both the rockbreaker and fpf features)

**Comment by FFXIVWytes** [comment]
Seems to have fixed it for me as well! Rockbreaker now updates properly!

**Comment by Grammernatzi** [comment]
Huh, very odd. Perhaps trying to tie it to gauge bugged it earlier? It didn't for me, though; perhaps because I was using the staging version of Dalamud. I'll just keep as it is, for now, at least.
