### ISSUE TITLE
Play into Astrodyne feature

### ISSUE THREAD

**Issue by 542673** [Grammernatzi/XIVComboPluginExpandedest#36]
The way it works currently, it just replaces draw/play (i also use draw into play feature) into astrodyne whenever the player has 3 seals, however with the way the job works, you'd still want to be able to draw a card while holding astrodyne for divination windows, which you currently arent able to, so only play should be swapped to astrodyne

**Comment by Grammernatzi** [comment]
It shouldn't replace Draw, I swear I changed it so it wouldn't. I'll check again.

**Comment by 542673** [comment]
Have you tried with the Draw on Play feature? While using that it replaces draw aswell for me

**Comment by 542673** [comment]
nevermind, im sorry i was using your version just for this feature and deamitus' one for draw/play, which caused said issue. it works perfectly once i turned off the latter and enabled it on yours
