### ISSUE TITLE
Monk AoE Combo issue

### ISSUE THREAD

**Issue by geramaia** [Grammernatzi/XIVComboPluginExpandedest#37]
Hello, I realized that if you were to spam the hotkey with the (Four-point fury becomes AoE Combo chain in order of forms during perfect balance) feature, for some reason the third combo will go back to Shadow the Destroyer instead of Rockbreaker. I think it's because during perfect balance, Rockbreaker becomes Shadow of the Destroyer therefore during the third combo even though on the hotbar it shows Rockbreaker, when you press it you will perform Shadow of the Destroyer instead. I think when you're pressing the hotbar before the GCD and queuing the action, you will perform Shadow of the Destroyer. However if you don't queue the action, you will perform Rockbreaker. 

It'll be great if this can be solved. But even if it's not possible, no biggie just a minor issue. It'll just result in using Celestial Revolution instead of Rising Phoenix but you'll still get both Solar and Lunar Nadi and able to use Phantom Rush. So just a DPS loss in using Celestial Revolution instead of Rising Phoenix that's all

**Comment by Grammernatzi** [comment]
It's odd, I can't seem to fix it; I could make the MNK combo be based off Arm of the Destroyer instead of Rockbreaker for the time being, and that would fix it, but people might get confused as to why their combo stopped working when they were using Rockbreaker on their bar to start the combo.

**Comment by Grammernatzi** [comment]
I currently went with that fix for the time being, I'm leaving this open so that if people get confused and look in issues, they'll see what the problem is; combo needs to be set on the Arm of the Destroyer action or Shadow of the Destroyer action to avoid this bug.

**Comment by Grammernatzi** [comment]
Okay, now it creates the issue in reverse, rockbreaker happens if you queue the action before level 82; it's really messy, but I'd prefer the action to be fixed at endgame and be broken before that rather than the other way around. I'll try to figure out how to possibly fix it for good later, if I can possibly do so.

**Comment by geramaia** [comment]
Cool! Thanks so much man. Really appreciate all that you're doing!

**Comment by Grammernatzi** [comment]
Dumb idea, but I could put the main AoE combo on Masterful Blitz, and just have it simply turn back if you have three beast chakra. That might fix the issue. It's a band-aid, but it'd work.

**Comment by Grammernatzi** [comment]
Yep, that works. It's a weird fix, but it's the one without any bugs, so it'll have to work for now.
