### ISSUE TITLE
New Monk Combo Discussion

### ISSUE THREAD

**Issue by Megasder** [Grammernatzi/XIVComboPluginExpandedest#38]
I discovered the plugin a few days ago and since we have more freedom for skills I really like it more and began to think about more features, still if you think this is too much or is wrong just ignore these suggestions.

I have a few sugestions for Monk, but instead of letting you write all the code I tried to do it myself, but I dont know how to try them and is my first time so maybe the code is wrong written.. anyway I put the code at the end, first I will explain the changes.

### **1. BootshineCombo and DragonKickCombo:**
Basically trying to make the 1,2,3 combo in 1 button, but since monk has two 1,2,3 combos it needs to use 2 buttons.
I could have done it in 1 button but because of "Form Shift" and "Perfect Balance" I had to get more keybinds, but now at least we have more freedom of choose instead of being everything in 1 button.

**_1 Press._** 
The 2 will start the same, if they have "Leaden Fist" they will become "Bootshine", if not they will be "Dragon Kick"

**_2 Press._**
Now "Bootshine" will become "True Strike" and "Dragon Kick" will become "Twin Snakes"

**_3 Press._**
And Finally "Bootshine" will become "Snap Punch" and "Dragon Kick" will become "Demolish"

**------And now the "Formless Fist" buff------**
When using "Form Shift":

**_"Bootshine"_**
 If it has "Leaden Fist" it will become "Bootshine", if not it will be "Dragon Kick"
_(90% of times you wont have "Leaden Fist" when using "Form Shift", but just in case)_

**_"Dragon Kick"_**
If the player has the "Disciplined Fist" Buff it will become "True Strike".
if the player doesn't have the "Disciplined Fist" Buff it will become "Twin Snakes".
If the player has the "Disciplined Fist" Buff but in 5 seconds the buff will go off it will become "Twin Snakes".
_(Here I dont know how to check my own buff timers, so maybe the code here is wrong)_

**_"Form Shift"_**
_(I Choose to use "Form Shift" again because I still needed 3 buttons for the "Formless Fist" Buff and I didn't want to put another keybind, so instead
I used this because after you get the "Formless Fist" Buff you dont need to use the skill again until the buff wears off, so its a free keybind)_
If the target has the "Demolish" Debuff it will become "Snap Punch"
If the target doesn't have the "Demolish Debuff" it will become "Demolish"
If the target Has the "Demolish Debuff but in 5 seconds the debuff will go off it will become "Demolish".
_(I used the Bard "Iron Jaws Feature" for checking the enemy debuffs, but still maybe I did it wrong)_

**_-----The "Perfect Balance" combos-----_**
Based around the Monk AOE Combo from the plugin:

**_"Bootshine"_**
It will do "Dragon Kick" - "Bootshine" - "Dragon Kick"

**_"Dragon Kick"_**
It will do "Dragon Kick" or "Leaden Fist""Bootshine" -  "True Strike" or "Twin Snakes" if no buff or almost wears off - "Snap Punch" or "Demolish" if no debuff or almost wears off

### **2. Perfect North:**
This is more simple than the above one, is simply that when "Perfect Balance" is used it changes into "True North", it doesn't remove a keybind but it makes easier to use "True North" when in "Perfect Balance" since you almost always want to use "True North" when "Perfect Balance" is used, also it should work with "Perfect Balance Feature", just that "Masterful Blitz" have preference.

Here is the code so you can check if you can use it.

```
    public const uint
            TrueNorth = 7546,
	
	internal class MnkBootshineCombo : CustomCombo
    {
        protected override CustomComboPreset Preset => CustomComboPreset.MnkBootshineCombo;

        protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level)
        {
            if (actionID == MNK.Bootshine)
            {
                if (IsEnabled(CustomComboPreset.MnkBootshineBalanceFeature) && OriginalHook(MNK.MasterfulBlitz) != MNK.MasterfulBlitz)
                    return OriginalHook(MNK.MasterfulBlitz);
			
				Status? pb = FindEffect(MNK.Buffs.PerfectBalance);
                if (!HasEffect(MNK.Buffs.LeadenFist) && (HasEffect(MNK.Buffs.FormlessFist) || pb.StackCount == 3 || HasEffect(MNK.Buffs.OpoOpoForm)) && level >= MNK.Levels.DragonKick)
                    return MNK.DragonKick;

				if (HasEffect(MNK.Buffs.RaptorForm)
					return MNK.TrueStrike;

					
				if (HasEffect(MNK.Buffs.CoerlForm)
					return MNK.SnapPunch;
					
            }

				return OriginalHook(MNK.Bootshine);
				
        }
            return actionID;
    }

internal class MnkDragonKickCombo : CustomCombo
    {
        protected override CustomComboPreset Preset => CustomComboPreset.MnkDragonKickCombo;

        protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level)
        {
            if (actionID == MNK.TrueStrike)
			{
		if (IsEnabled(CustomComboPreset.MnkBootshineBalanceFeature) && OriginalHook(MNK.MasterfulBlitz) != MNK.MasterfulBlitz)
                    return OriginalHook(MNK.MasterfulBlitz);
				
				Status? pb = FindEffect(MNK.Buffs.PerfectBalance);
                if ((HasEffect(MNK.Buffs.LeadenFist) && HasEffect(MNK.Buffs.OpoOpoForm)) ||  pb.StackCount == 3 )
                    return MNK.Bootshine;
				
				if (!HasEffect(MNK.Buffs.LeadenFist) && pb.StackCount == 3 ) && level >= MNK.Levels.DragonKick)
                    return MNK.DragonKick;	
				
				if (HasEffect(MNK.Buffs.RaptorForm) && level >= MNK.Levels.TwinSnakes)
					return MNK.TwinSnakes;
				
				if (pb.StackCount == 2))
                    var fist = FindOwnEffect(MNK.Buffs.TwinSnakes);
					if (fist is not null)
                    {
                        if (fist?.RemainingTime < 6)
                            return MNK.TwinSnakes;
                        return MNK.TrueStrike;
                    }
					if (fist is null)
					{
						return MNK.TwinSnakes;
					}
					
				if (pb.StackCount == 1)
				{
                        var demolish = FindTargetEffect(MNK.Debuffs.Demolish);
					if (demolish is not null)
                    {
                        if (demolish?.RemainingTime < 6)
                            return MNK.Demolish;
                        return MNK.SnapPunch;
                    }
					
					if (demolish is null)
					{
						return MNK.Demolish;
					}
				}

					
				if (HasEffect(MNK.Buffs.CoerlForm) && level >= MNK.Levels.Demolish)
					return MNK.Demolish;
			}	
			
			return OriginalHook(MNK.DragonKick);
				
		}
		
		Status? pb = FindEffect(MNK.Buffs.PerfectBalance);
        if ((actionID == MNK.FormShift) && (HasEffect(MNK.Buffs.FormlessFist)) || pb.StackCount == 1)
        {
            var demolish = FindTargetEffect(MNK.Debuffs.Demolish);
				if (demolish is not null)
            {
                if (demolish?.RemainingTime < 6)
                   return MNK.Demolish;
                return MNK.SnapPunch;
            }
					
				if (demolish is null)
			{
				return MNK.Demolish;
			}
					
			return OriginalHook(MNK.FormShift);
        }
		
		return actionID;
	}	


	
	
internal class MonkPerfectNorth : CustomCombo
    {
        protected override CustomComboPreset Preset => CustomComboPreset.MonkPerfectNorth;

        protected override uint Invoke(uint actionID, uint lastComboMove, float comboTime, byte level)
        {
            if (actionID == MNK.PerfectBalance)
            {
				if (HasEffect(MNK.Buffs.PerfectBalance))
					return TrueNorth;
				
            }
            return OriginalHook(MNK.PerfectBalance);
            
        }
        return actionID;
    }
```

I have other suggestions for jobs like Scholar or Sage but these will be another day, but in short make that Schoolar skills that require a summon summon the fairy (with the option in the plugin to choose wich one) and that every skill that uses Aetherflow will change into well "Aetherflow". As for sage any skill that require "Addersgall" become "Rhizomata" if you dont have any charges, well anyway these are just toughts that I had today so maybe later I will change my mind.

Anyway thank you for the amazing plugin and for checking our request, and sorry for making you look into my code XD

**Comment by Megasder** [comment]
Sorry I couldn't reply before real life stuff :( yeah I already supposed that you had already thought about making monk combo changes, but still wanted to do the suggestion, sorry :(

For the true North feature you are right, I was watching an older video of a mnk combo that said that you always want true north with the perfect balance, but now with the positional changes yeah is obsolete...

As for the main problem from the combo that is too automated maybe I will think for a way but I can't make promises since you already tried to do it XD.

**Comment by Megasder** [comment]
Maybe I have a solution, just tell me if it can be done.
I will try to explain with images and not try to write any code for now since is only a test, the only problem really is the "Formless Fist" (damm that skill XD) for the other is pretty simple. So let's begin:


### **NORMAL COMBO**
**Minimal amount of hotkeys to make it work: 2**
This is the same as I put above, however I will put images now to make it clearer
_NOTE: If you have the "Leaden Fist" Buff "Dragon Kick" will ALWAYS be "Bootshine" except if I put a note that says otherwise_ 
![bootshine](https://user-images.githubusercontent.com/92712466/146358345-f1f1745a-b0c5-41ec-8302-e2a039ee3e2a.JPG)

![dragonkick](https://user-images.githubusercontent.com/92712466/146358364-476c9b8a-b1de-4531-b604-265b4f56d93a.JPG)

**OUT OF COMBAT/NO FORM**
![outcombat](https://user-images.githubusercontent.com/92712466/146358540-b5b88f21-d283-4f10-9b89-42548cd50215.JPG)
Keybind 1: "Dragon Kick"
Keybind 2: "Dragon Kick"
_The 2 keybinds start the same, if no form and no "Leaden Fist", "Dragon Kick". even with "Leaden Fist" if you dont have the opo opo form is not a critical hit and has lower potency, so better start always with "Dragon Kick"_

**OPO-OPO FORM**
![opoopo](https://user-images.githubusercontent.com/92712466/146359716-227bc095-f9d0-455b-9614-88ac954ae7c1.JPG)
Keybind 1: "Dragon Kick" - "Leaden Fist" "Bootshine"
Keybind 2: "Dragon Kick" - "Leaden Fist" "Bootshine"

**RAPTOR FORM**
![raptor](https://user-images.githubusercontent.com/92712466/146360094-221256d6-354d-48e0-9974-b49ebc80fee0.JPG)
Keybind 1 = "True Strike"
Keybind 2  = "Twin Snakes"

**COEURL FORM**
![coeurl](https://user-images.githubusercontent.com/92712466/146360423-4f402769-66df-404e-b7b8-54a20fa791c6.JPG)
Keybind 1 = "Snap Punch"
Keybind 2 = "Demolish"

### **PERFECT BALANCE**
**Minimal amount of hotkeys to make it work: 3**
Since it needs 3 keybinds instead of using another combo one I just checked the skills that are not going to be used while you are under the "Perfect Balance" state, so finally decided to use the skill itself since u dont want to use "Perfect Balance" or "Form Shift" while you are in that state, never.
**OUT OF COMBAT/NO FORM/NO STACKS**
![perfectbalanceout](https://user-images.githubusercontent.com/92712466/146360986-b1d3bacd-55a7-4400-9edc-8701826f04fb.JPG)
When there are no stacks this is how it should look, 

**3 STACKS**
![balance3stacks](https://user-images.githubusercontent.com/92712466/146362283-04efaa71-cb4a-4193-bc9f-ac31a180abfb.JPG)
Keybind 1: "Dragon Kick" - "Leaden Fist" "Bootshine"
Keybind 2: "Dragon Kick" - "Leaden Fist" "Bootshine"
Keybind 2: "Dragon Kick" - "Leaden Fist" "Bootshine"

**2 STACKS**
![balance2stacks](https://user-images.githubusercontent.com/92712466/146362484-3c1b749f-5ccd-4149-8e7d-b6c8e706cc41.JPG)
Keybind 1: "True Strike"
Keybind 2: "Twin Snakes"
Keybind 3: "Dragon Kick" - "Leaden Fist" "Bootshine"

**1 STACK**
![balance1stacks](https://user-images.githubusercontent.com/92712466/146362767-9a630825-7804-409a-a778-3ccc586488f2.JPG)
Keybind 1: "Snap Punch"
Keybind 2: "Demolish"
Keybind 3: "Dragon Kick" - "Leaden Fist" "Bootshine"

_So by looking into the keybinds you can check that keybind 1 and 2 are for 3 different Form Chakras, while keybind 3 is to get 1 type of Form Chakra. But because of your AOE combo maybe you want to change that keybind 1 is for 1 type of Form Chakra and 2 and 3 for the 3 different Form Chakras. do as you wish._

And finally the big boss, the Formless Fist, oh boy

### **FORM SHIFT**
**Minimal amount of hotkeys to make it work: 4**
![formless](https://user-images.githubusercontent.com/92712466/146363982-8b5644be-6f87-4f6c-94e5-dcfd44d8f401.JPG)
This is how it should look at the end using the 4 hotkeys.

_Here I want to make a note, like before I needed another hotkey and didnt want to get a combo one, so im using the "Form Shift" itself to change into another skill, but there is a problem, 90% of times when you are under the effect of "Formless Fist" u don't want to use "Perfect Balance", but what happens if you missclick a keybind and used "Form Shift" instead? The only solution I found is that right click the "Formless Fist" buff icon to remove it, so "Perfect Balance" returns and you can use that skill, but like I said, it happening is extremely rare so I suppose is not a problem._

**FORMLESS FIST**
![formlessfist](https://user-images.githubusercontent.com/92712466/146364856-56e88c87-5207-4522-8992-bc73148f5d9c.JPG)
Keybind 1: "Dragon Kick" - "Leaden Fist" "Bootshine"
Keybind 2: "Twin Snakes"
Keybind 3: "Demolish"
Keybind 4: "Snap Punch"

NOTE FOR SNAP PUNCH
I dont think its posible, but is there a way to detect if you are in the rear or the flank of a target? because in "Formless Fist" this would be a perfect feature for the "Snap Punch" since "Snap Punch" has more potency than "True Strike" only on the flank, so its better to use "True Strike" on the rear. 
Basically the keybind 4 is for the Big Hit skill, if there is a feature that checks that you could make that if you are on the flank use "Snap Punch"
![flank](https://user-images.githubusercontent.com/92712466/146366029-2da2aa01-8a86-4f22-8e46-b712f57e6c08.JPG)
And if you are on the rear use "True Strike"
![rear](https://user-images.githubusercontent.com/92712466/146365715-7e7bf1b3-6de9-4bdc-b774-90e7560e78ef.JPG)
And when using "True North" is always "Snap Punch"
![rearnorth](https://user-images.githubusercontent.com/92712466/146365884-3cbeba12-eec7-4d58-bfbb-9271a7241236.JPG)

Of course if there is no way of checking that you are on the rear or the flank just make that is always "Snap Punch", Anyways when you use "Formless Fist" you are not going to use "Snap Punch" or "True Strike" in most cases XD

So tell me what you think about this.

**Comment by Grammernatzi** [comment]
I'll take a look at it and see how it can be implemented; I don't think auto positionals would be a good idea. That said, I think it wouldn't be necessary and you rarely if ever true strike out of form shift, and I can't think of a case where doing so instead of snap punch or dragon kick/bootshine would be better. I'll put it in as a WIP feature if it plays nice.

**Comment by Grammernatzi** [comment]
Alright, I added it in, putting an (Experimental) tag on it. Tell me your thoughts when you get the chance.

**Comment by ParasiteXX** [comment]
Seems to work pretty well. Will take some getting used to. Only odd issue is that when I have Monk Boothsine Feature on, TwinS and TrueS will shift to Bootshine if in no form or Leaden Fist.

**Comment by Grammernatzi** [comment]
> Only odd issue is that when I have Monk Boothsine Feature on, TwinS and TrueS will shift to Bootshine if in no form or Leaden Fist.

Yeah, this was due to a typo on my end, pushing a fix right now.

**Comment by ParasiteXX** [comment]
Preliminary testing and everything seems to work perfectly now.

**Comment by Grammernatzi** [comment]
One thing I thought of it is that it might be good to have an option that leaves Form Shift alone; since as far as I can see, Snap Punch is basically useless in Formless Fist. I've not had to use it once, since if I have both Twin Snakes/Demolish up, I just use Dragon Kick/Bootshine. It'd probably just be an optional feature, but that way you could keep Form Shift up instead of having to wait for it to run out before re-applying it.

**Comment by victorkikudome** [comment]
Thank you for your work Grammernatzi, it works flawlessly.

**Comment by ParasiteXX** [comment]
Yeah. I see no reason to ever use Snap Punch during formless. Pretty much all other attacks are much higher priority choices.

**Comment by Megasder** [comment]
Yep, I suggested the "Formless Fist" so you can have all the options avaiable, but is true that "Formless Fist" is used to open with "Dragon Kick", or a fast buff or debuff, you are not gonna use it to attack.

However I checked some high level rotations and they use the "Twin Snakes"  with "Perfect Balance" at the begginning, not at 2 stacks, to get the buff early, so let me put another suggestion for the "Perfect Balance"

### **PERFECT BALANCE**
**CURRENT CHAKRA: NONE**
_Note: It doesnt use the stacks to get the skills, it will use the current beast gauge that you are on._

![0](https://user-images.githubusercontent.com/92712466/146638990-31214a06-cc03-4c68-b8cc-5da8824f2bc6.JPG)
Keybind 1: "Twin Snakes"
Keybind 2: "Demolish"
Keybind 3: "Dragon Kick"/"Leadin Fist""Bootshine"

_Same as "Formless Fist", the first skill you wanna use for "Perfect Balance" is to buff yourself, debuff the enemy or "Dragon Kick"/"Bootshine"
Because of this if we use the "Perfect Balance" Stacks to change the skills it will be a mess, instead if we use the current "Beast Chakra" it will be much easier since it wont matter wich skill you use first, it will always continue the right combo._

_(Lets say for example that we use "Twin Snakes" first (at 3 stacks), when we  are at 2 stacks we will get:_
![3](https://user-images.githubusercontent.com/92712466/146638667-fce73786-10b3-4bf2-b744-699a0374571b.JPG)
_Making it you get 2 coeurl chakras instead of 1-2-3, so its better to use the current beast chakra to check combos)_


_Note: for the images I just put the chakras in the first spot, but in live it should work in any spot._
**CURRENT CHAKRA: OPO-OPO**
![2](https://user-images.githubusercontent.com/92712466/146638728-31cc2b78-91f7-40f6-b1fc-6a02d342424b.JPG)
Keybind 1: "True Strike"
Keybind 2: "Twin Snakes"
Keybind 3: "Dragon Kick"/"Bootshine"

**CURRENT CHAKRA: COEURL**
![5](https://user-images.githubusercontent.com/92712466/146638785-c9af6dd1-8483-4fe7-a3b7-01285b800ecc.JPG)
Keybind 1: "Snap Punch"
Keybind 2: "Demolish"
Keybind 3: "Dragon Kick"/"Bootshine"

**CURRENT CHAKRA: RAPTOR**
![6](https://user-images.githubusercontent.com/92712466/146638822-e20f0d42-a8aa-445b-a13d-3c522da63244.JPG)
Keybind 1: "Dragon Kick"/"Bootshine"
Keybind 2: "Dragon Kick"/"Bootshine"
Keybind 3: "Dragon Kick"/"Bootshine"

Well these were the changes for perfect balance, now I wanna talk about a new feature.

### **EASIER MASTERFUL BLITZ**
Depending if you have Lunar or Solar Nadi, the combo changes to get the other one.

The changes for "Perfect Balance" above are if you dont have any Nadi or you have both Solar and Lunar.

This is actually a Hold Hand feature, making that you cant miss your nadis, getting always the one you dont have, its not really a necesary feature but still maybe people like it, still maybe is a mess to make, so if you dont want to make it dont do it XD.

**CURRENT NADI: SOLAR**
![7](https://user-images.githubusercontent.com/92712466/146639378-33d58fd4-cc84-4ffb-8e0d-4b0a8544909a.JPG)
Doesn't matter with Beast Chakra you have, you need to use the same move all 3 times, so its the same Hotbar for all 3 steps

**CURRENT NADI: LUNAR**
**CURRENT CHAKRA: OPO-OPO**
![8](https://user-images.githubusercontent.com/92712466/146639532-15ac41ba-b3aa-469c-913b-1d1951a02191.JPG)
Keybind 1: "True Strike"
Keybind 2: "Twin Snakes"

**CURRENT CHAKRA: COEURL**
![9](https://user-images.githubusercontent.com/92712466/146639699-e2454912-ddeb-42f1-9639-71be0e77125d.JPG)
Keybind 1: "Snap Punch"
Keybind 2: "Demolish"

**CURRENT CHAKRA: RAPTOR**
![10](https://user-images.githubusercontent.com/92712466/146639701-caa090d2-f8a5-4f1a-b0f8-ed6286d015af.JPG)
Keybind 1: "Dragon Kick"/"Bootshine"
Keybind 2: "Dragon Kick"/"Bootshine"

I Checked the new "Monk AoE Combo Form Shft Option" and has the same problem for the "Perfect Balance", maybe you want to use "Four-point Fury" to get the buff first, but then the stacks break the combo, so you should do the same as I said before, use the current beast chakra to determine the next combo.

So it should look like this.
### **PERFECT BALANCE AOE**
**CURRENT CHAKRA: NONE**
![11](https://user-images.githubusercontent.com/92712466/146640100-b1229747-c5d9-49e6-aad3-567c76c0960f.JPG)
Keybind 1: if level < 82 = "Rockbreaker" else  "Shadow of the Destroyer"
Keybind 2: "Four-point Fury"

**CURRENT CHAKRA: OPO-OPO**
![12](https://user-images.githubusercontent.com/92712466/146640237-d2d4845c-34e1-403a-a71d-8368a0dbb705.JPG)
Keybind 1: if level < 82 = "Rockbreaker" else  "Shadow of the Destroyer"
Keybind 2: "Four-point Fury"

**CURRENT CHAKRA: COEURL**
![13](https://user-images.githubusercontent.com/92712466/146640375-80809aa7-c9df-4193-9a40-8236e1e42282.JPG)
Keybind 1: if level < 82 = "Rockbreaker" else  "Shadow of the Destroyer"
Keybind 2: "Rockbreaker" ALWAYS (for the 1-2-3 combo)

**CURRENT CHAKRA: RAPTOR**
![14](https://user-images.githubusercontent.com/92712466/146640517-c76d9668-6586-4087-b821-7e48905b6ba1.JPG)
Keybind 1: if level < 82 = "Rockbreaker" else  "Shadow of the Destroyer"
Keybind 2: if level < 82 = "Arm of the Destroyer" else  "Shadow of the Destroyer"
_Sorry for the image im still level 80._

As for the easier masterful blitz, make that if you have solar nadi the 2 keybinds are : 
if level < 82 = "Rockbreaker" else  "Shadow of the Destroyer"

and if you have lunar nadi make the 1-2-3 combo

Keybind 1: if level < 82 = "Arm of the Destroyer" else  "Shadow of the Destroyer" 
Keybind 2: "Four-point Fury" (To start the combo with the buff)

and then just follow the current beast chakra again, more simple than the single target combo I think.

And this is pretty much the things I had in mind these past few days testing monk, what do you guys think?

**Comment by Grammernatzi** [comment]
I don't want to make things TOO automatic, but I am going to look at how to make perfect balance work with an optimal rotation. Though, I'm going to be busier than usual today, so I don't know how long it will take.

**Comment by Grammernatzi** [comment]
I made something that combines a bit of what you suggested and some stuff I thought of myself; take a look if you can. I'm no Monk main, but I made it while reading the resources off The Balance, so I'm hoping it works well enough.

**Comment by Megasder** [comment]
Sorry for all the trouble... :(

I found a bug with the new perfect balance when you start with "Twin Snakes" and "Demolish".

If you start with "Twin Snakes" the next options are "Snap Punch" and "Demolish" and then it becomes "Snap Punch" and "Demolish" again, making that you get 2-3-3 chakras, so bad one.

If you start with "Demolish" the next options are "True Strike" and "Twin Snakes" and then "Snap Punch" and "Demolish" again, making that you get 3-2-3 chakras, so bad one too.

Im also not a monk main but still I like it and I think is the one that deserved more love for combos since the endwalker patches.

**Comment by Grammernatzi** [comment]
That was intentional, because I didn't want it to be TOO brainless and so that you'd have to press 2-2-3 instead of just 2-2-2, but I can make it so that it turns into opo-opo. I wanted it to not be too simple, but I can understand wanting it to be a simple one button thing.

**Comment by Megasder** [comment]
Nah its okay, I tought it was a bug since it was not explained in the  description. If there is no explanation you expect to be everything at 1 button XD. 

For me its good, but maybe for people it will be a bit mess. Still good job making it :)

**Comment by Grammernatzi** [comment]
Yeah, I can edit the description to make it more obvious, at least. I like the idea that you have to sort of know what you're doing, rather than just mash the button. But I still like the idea of saving buttons, especially for friends of mine that are disabled. This way they can still have the 'full experience' of playing MNK but keep everything on the face buttons on a controller.

**Comment by ParasiteXX** [comment]
Not sure if mentioned yet. But I would also put Four-point Fury at start of rotation for AOE. As you wanna set or refresh that buff at the start of PB combo most of the time.

**Comment by Grammernatzi** [comment]
Yeah, I'll do four-point fury as well. And maybe I'll make an optional feature for blitz as well that adds opo-opo.

**Comment by ParasiteXX** [comment]
After testing for a bit, 2-2-3 didn't feel as bad as I thought it would. Got used to it pretty fast. But I can see some people still preferring a simpler braindead option ;)

**Comment by Grammernatzi** [comment]
Personally it's more of a preference on my end, I like having to make
choices in my rotation but I also prefer my hotbar to be nice and
condensed. So that's why I made it optional, same with the new Red mage
combo feature, but I still left the old one in for people who prefer it.

**Comment by jjgitprojects** [comment]
Hi Dev sir, I have a suggestion/issue to raise with regards to one particular detail about the experimental monk combo options.

I appreciate the option that leaves Form Shift alone, instead of turning it into Snap Punch. 
In the same line of thinking, I was wondering if there can be _**an option to leave Perfect Balance alone instead of turning it into Demolish**_ when under the effect of Formless Fist (effect of using Form Shift). 

---------------------------------------
This option will enable a player to execute (or even weave) another Perfect Balance should he desire to, because otherwise without this feature, even if there are remaining charges on Perfect Balance, it can **NEVER** be used _IMMEDIATELY_ until the subsequent Demolish (or any subsequent GCD) is used, hence preventing back-to-back usages of Perfect Balance (i.e needing to spend at least 1 GCD in order to get back the Perfect Balance button).

I am a MNK player myself so I understand that for the most optimal DPS rotation, there is an optimal window to use Perfect Balance in such a way that you should not chain 2 Perfect Balance chains immediately after each other. However, this is mostly true only for encounters that last longer than 2 Perfect Balance-to-Masterful Blitz chains, such as Boss fight rotations. There are practical situations, such as in big AoE situations (big trash pulls in dungeon etc.) when you just want to deal the most burst AoE damage in a short window, which is very often in duties such as dungeons. Hence, having the option to leave Perfect Balance alone (aside from being converted to Masterful Blitz when in possession of 3 beast chakras) could be quite a practical benefit for most players. 

Ultimately yes, we are only saving 1 GCD worth of time which some could argue is not worth losing the functionality of Perfect Balance turning into Demolish, which I will acknowledge is useful ONLY IF you end up in the very specific situation that you need to refresh the Demolish DOT (WITHOUT needing to refresh the Twin Snakes/Disciplined Fist buff) immediately after PB. But hence, my personal opinion is that it is not meant to be a common situation you find yourself in (i.e you did not use PB in the "optimal DPS" window of your rotation, which should follow the Opo-opo GDC IMMEDIATELY after refreshing Discipline Fist buff and Demolish DOT successively), such that I would just keybind a stand-alone Demolish separately to take into account this particular situation should it ever happen. I feel that an optimal MNK player would find himself with a greater need to execute back-to-back PBs instead of losing the ability to do so, for just 1 particular non-optimal situation.
-----------------------------------

Feel free to consider this suggestion in your own capacity and judgement! I very much appreciate the work you for the MNK combos regardless!
