### ISSUE TITLE
Astrodyne

### ISSUE THREAD

**Issue by 542673** [Grammernatzi/XIVComboPluginExpandedest#40]
Astrodyne should replace draw aswell when its on cooldown, there are cases where i had 3 seals and duo to draw being on cooldown Astrodyne wouldnt show up

**Comment by Grammernatzi** [comment]
It's meant to be a helper, not to replace a button. That was the reason they asked for it. They are not mutually exclusive actions and you want to use one without the other. It was a requested feature, so it isn't necessarily meant to be a perfect replacement.

**Comment by Grammernatzi** [comment]
Added a disclaimer in newest version to prevent confusion.

**Comment by Grammernatzi** [comment]
Okay, I actually see what you meant now, I somehow misread it; so I'll add it real quick

**Comment by Grammernatzi** [comment]
Added, sorry about that.
