### ISSUE TITLE
SGE AoE suggestion

### ISSUE THREAD

**Issue by romabord** [Grammernatzi/XIVComboPluginExpandedest#41]
98 Phlegma into Dyskrasia: Phlegma turns into Dyskrasia when you are out of charges.
-
I suggest to add Toxicon over Dyskrasia if it is possible, so full AoE will stay on 1 button. - Phlegma-Toxicon-Dyskrasia.
Cheersies!

**Comment by Grammernatzi** [comment]
Added in newest version.
