### ISSUE TITLE
Ninja Forked Raiju not turning into Fleeting Raiju

### ISSUE THREAD

**Issue by Impurities** [Grammernatzi/XIVComboPluginExpandedest#43]
Ninja's Forked Raiju feature on Aeolian Edge, Armor Crush and Huraijin are not following up into Fleeting Raiju when having multiple stacks of Forked Raiju, which is a common occurrence starting off your opener, this is also impossible to do without the plugin since Forked Raiju turns into Fleeting Raiju:

Video for reference, current effect vs expected: https://streamable.com/boqvgt

Thank you very much for your work on this plugin fork!

**Comment by Grammernatzi** [comment]
Yeah, I didn't know it could stack and Daemitus (who programmed the feature) didn't either. I can easily fix this by just checking to see if the action is changed, though. Please let me know if that fixes it since I can't test, I'll push the update in a second.

**Comment by Impurities** [comment]
> Yeah, I didn't know it could stack and Daemitus (who programmed the feature) didn't either. It seems he fixed it by just changing the priority of the actions. Please let me know if it works, since I can't test it myself.

Can confirm, working as intended now! Thank you!
