### ISSUE TITLE
Suggestion: SCH - Change all spells that use Aetherflow stacks to Aetherflow when no stacks.

### ISSUE THREAD

**Issue by ryande87** [Grammernatzi/XIVComboPluginExpandedest#45]
Would love to have the option to change all aetherflow-used abilities (Excog, Sacred Soil,  Lustrate, and Indom) to Aetherflow when at zero stacks, or not buffed by Recitation.

**Comment by Grammernatzi** [comment]
I can try to add this in the future, but since energy drain already does this it's not really a huge priority

**Comment by Grammernatzi** [comment]
Eh, it was easy enough, so I added it while fixing how Shoha worked for Ogi Namikiri.

**Comment by ryande87** [comment]
I just saw the update. I appreciate the effort. Please enjoy your holidays!
