### ISSUE TITLE
[SAM] #123 'Ikishoten Namikiri Feature' makes Ikishoten also become Shoha

### ISSUE THREAD

**Issue by Dosudude** [Grammernatzi/XIVComboPluginExpandedest#46]
When using 'Ikishoten Namikiri Feature' there seems to be an extra functionality that makes your Ikishoten button become Shoha when it is ready. If possible, I would prefer this to be split into a separate feature to avoid confusion.

**Comment by Grammernatzi** [comment]
This is how it works in the original feature on the original fork, I just ported it over, I can change it but I just made it the same to prevent confusion
