### ISSUE TITLE
Question about evil 

### ISSUE THREAD

**Issue by sauronshotdogs** [Grammernatzi/XIVComboPluginExpandedest#47]
Basically, what makes them evil(or extra)?

**Comment by Grammernatzi** [comment]
It's just a joke of mine, they're evil (reverse) versions of the normal combos. I just made them secret so they didn't clog up the normal list, since most people won't use them. I added them for the stupid reason of being able to spam whatever aoe moves I wanted for silly shenanigans.

**Comment by sauronshotdogs** [comment]
Aha, that makes sense. Thanks for the quick response!
