### ISSUE TITLE
BRD: WM into PP is sometimes bugged out

### ISSUE THREAD

**Issue by curtis846** [Grammernatzi/XIVComboPluginExpandedest#49]
As titled. I could not reliably reproduce it but it has come up from time to time. When it happens, WM icon will continue to show and PP can only be seen/pressed for a split second. Will continue to be like this until restarting client.

**Comment by Grammernatzi** [comment]
I reverted it back to gauge-based logic, has this helped?

**Comment by curtis846** [comment]
I must say I am no developer and if there is a new build I am not aware. Dalamud shows no updates found. 
With that said, i just encounter this again after restart, in my second ex1 run. Here is what I observed:
Opener: PP split second only happens on 42/39/36/33 etc. If you spam at those intervals you can get it out.
After that, PP seems random. There is one rotation where it seems normal again, but bugged out again 20 seconds in WM.

**Comment by Grammernatzi** [comment]
I just pushed the new build. I had forgotten to send it to github, so just
right now it went up. Tell me again if it works when you update it. Also,
it goes without mentioning, but you're not using any other XIVCombo
plugins, yes?

**Comment by curtis846** [comment]
Thanks for the quick fixes and hard work maintaining the plugin. Looks good now.
