### ISSUE TITLE
Bard proc saver

### ISSUE THREAD

**Issue by 542673** [Grammernatzi/XIVComboPluginExpandedest#50]
Similar to what Dancer has on flourish, would it be possible to have a Barrage proc saver, replacing baragge with straight shot or refulgent arrow?

**Comment by Grammernatzi** [comment]
I can see this, but doesn't the heavy/burst shot feature already do this? You don't want to use burst shot if you have barrage up, and you don't want to use it if you have straight shot ready either (since it may overwrite the proc).

**Comment by 542673** [comment]
it's more of a helper since sometimes you might wanna barrage on first weave and end up wasting a straight shot proc, its no big deal wheter its implemented or not just thought it'd be nice to have

**Comment by Grammernatzi** [comment]
Fair enough, I'll close for now but I may add it in the future.

**Comment by Grammernatzi** [comment]
Added
