### ISSUE TITLE
Bard: Radiant Finale / Battle Voice

### ISSUE THREAD

**Issue by idecibel** [Grammernatzi/XIVComboPluginExpandedest#51]
Thanks again for doing the lords work.

I don't play Bard that often, but it seems to me like  you'd always want to use these in concert. 
Maybe you thought about it and it's something you don't wanna add but didn't see it mentioned so thought I should bring it up.

Radiant Finale could become Battle Voice when;
a. You are sub level 90 (synch or otherwise)
b. Radiant Finale is on cooldown.

Let me know what you think!

Best regards and happy holidays!

**Comment by Grammernatzi** [comment]
Maybe if there's a way to detect coda. Because you can't use it without coda, and you *shouldn't* use it without max coda. Battle Voice becoming Radiant Finale if you have 3 coda and it's off-cooldown is likely how I'd go about it.

**Comment by Grammernatzi** [comment]
Added

**Comment by idecibel** [comment]
Thanks!
Though I'm not sure we should keep the coda requirement;
- In the opener you will use it with 1 coda
- Subsequent uses will indeed always be with 3 barring any major event preventing you from entering all 3 songs.

Thinking about other scuffed cases or dungeons where things are not aligned etc, I think if you pop battle voice you potentially want to use radiant finale independent of the stacks.

 The safest bet for this feature might be battle voice = if on cooldown=> radiant finale - and leave it up to the player skill/determination/situation if they want to also pop radiant finale at that moment based on their stacks.

**Use cases**
_Opener:_ I want to use BV and RF with 1 stack <not possible today>

_Burst windows:_ I want to use BV and RF with 3 stacks <possible>

_Dungeons:_ I used WM on the first small pull, now I'm in MB and we're doing a monster pull: I want to use BV and RF 2 stacks <not possible today>

What do you think?

**Comment by Grammernatzi** [comment]
Fair enough, from what I see you use battle voice and radiant finale at the same time, in the same weave window, so the priority for each likely doesn't matter. So I'll set it so that it prioritizes battle voice, and then radiant finale.

**Comment by Grammernatzi** [comment]
Okay, I adjusted it so it doesn't rely on Coda, Battle Voice just replaces Radiant Finale if it's on cooldown; that seems like it wouldn't cause any issues with the opener/rotation, from what I can see.

**Comment by idecibel** [comment]
thanks sir, indeed i think it's good like this!

**Comment by Grammernatzi** [comment]
Also went ahead and added a second, optional feature that adds Raging Strikes to Radiant Finale as well, so they all share a single button. The priority should be the way it works in the opener.
