### ISSUE TITLE
Bard: Empyreal Arrow / Sidewinder

### ISSUE THREAD

**Issue by Megasder** [Grammernatzi/XIVComboPluginExpandedest#52]
Im not a bard main but after leveling it up recently I noticed these 2 skills.

Maybe "Empyreal Arrow" and "Sidewinder" can share a keybind since both are just OGCD skills that you want to use when they are up.

Since "Sidewinder" has the longer cooldown, make that "Empyreal Arrow" changes to "Sidewinder" if its up, so you can put "Sidewinder" to any hotbar to check the cooldown if you want.

**Comment by idecibel** [comment]
If he does this I would suggest having it the other way around, Sidewinder => Empyreal Arrow when EA is ready.
EA is used first in the opener and I guess since SW is the bigger cooldown; its best not to gate smaller stuff with it, in case you ever want to hold it for buffs or whatever. idk!

**Comment by Grammernatzi** [comment]
This could possibly be done, likely the way idecibel mentioned. I can look into it.

**Comment by Grammernatzi** [comment]
Added
