### ISSUE TITLE
Less of a issue more of a question

### ISSUE THREAD

**Issue by F-a-y-t-h** [Grammernatzi/XIVComboPluginExpandedest#53]
But is there a good way to prevent ogcd skill that shouldn't be double weaved but they are capable of doing so if your distracted and are mashing.
Mostly thinking of Bloodstalk/Gluttony when Soul Reaver is up and Hissatsu: Kaiten

**Comment by Grammernatzi** [comment]
I mean, maybe. Could replace them with iaijutsu and gibbet/gallows. I might look at it in the future.

**Comment by Grammernatzi** [comment]
Added both of those examples.
