### ISSUE TITLE
Dragoon: Geirskogul/Nastrond into Stardiver

### ISSUE THREAD

**Issue by Megasder** [Grammernatzi/XIVComboPluginExpandedest#54]
Since Blood of the Dragon is now a trait Stardiver is now his own button, so maybe we could make that when you are in Life of the Dragon mode and Nastrond is on cooldown swap it with Stardiver.

**Comment by Grammernatzi** [comment]
Possibly, that doesn't sound too bad. I'll give it a look in the future.

**Comment by Grammernatzi** [comment]
Added
