### ISSUE TITLE
Suggestion: Change Fire 4 to Fire 1 when astral fire is at 4 or lower

### ISSUE THREAD

**Issue by AwesomeJames2120** [Grammernatzi/XIVComboPluginExpandedest#58]
Title essentially. I have a very small lizard brain that has difficulty counting/looking at timers while in combat

**Comment by Grammernatzi** [comment]
I added this before but it went too far and got me in trouble with the Dalamud mods, so, sadly, this won't happen again, unless Daemitus decides to add it to his own fork.
