### ISSUE TITLE
Reaper: Apply "Death's Design" Debuff Check

### ISSUE THREAD

**Issue by Megasder** [Grammernatzi/XIVComboPluginExpandedest#59]
This wont remove any keybind but is more of a opsie check, you want always the 
"Death's Dessing" debuff on your target, so if you have selected a enemy that doesn't have the debuff from you it changes the "Slice" Combo into "Shadow of Death" and "Spinning Scythe" Combo into "Whorl of Death". You still want to have these 2 skill in your hotbar if you want to extend the debuff.

This is more for people like me that forgets to reapply the debuffs and loses tons of dps because I havent applied the debuff all fight XD

**Comment by Grammernatzi** [comment]
Unfortunately, same thing I mentioned in the auto fire 1 and the monk combo thing, I'm not adding auto upkeep features; besides, I feel that does lean more towards the 'cheat' territory, and I've been trying to avoid that for a while (outside of features Daemitus has as well).

**Comment by F-a-y-t-h** [comment]
Not to mention that debuffs can get a little fhunky when dealing with content with high amount of people so it has a high risk of breaking in crowded fates or other content with > 24 people.

**Comment by Megasder** [comment]
Fair enough, I will just dont forget to apply it in fights XD

**Comment by Grammernatzi** [comment]
I'd recommend installing Job Bars at least. You can set it to beep at you if it reaches a certain threshold (say, 5s) and also make the icon light up when you need to apply it. That's helped me a lot with remembering it, and especially has helped me with remembering things on Bard.
