### ISSUE TITLE
GNB Burst Strike parity with Fated Circle

### ISSUE THREAD

**Issue by Nilhfaith** [Grammernatzi/XIVComboPluginExpandedest#60]
Hi! Would it be possible to add a feature for GNB that adds Burst Strike to the single target combo when the charges are full similar to how the Fated Circle feature works? Or would that be too much automation?

**Comment by Grammernatzi** [comment]
I believe Daemitus added this as a 'secret' combo to his plugin, so I will probably do so later. Though, I won't add it to other tanks unless he does so, as well.

**Comment by Nilhfaith** [comment]
Neat, thank you! c:
