### ISSUE TITLE
XIVcombo breaks mouseover plugins.

### ISSUE THREAD

**Issue by Clickeddaisy** [Grammernatzi/XIVComboPluginExpandedest#63]
Like the title says abilities modified with this plugins breaks mouseover plugins like DelvUI and Mouseover Action.

Is this fixable or is it something we just have to deal with?

**Comment by F-a-y-t-h** [comment]
Unless changed in his last update MOAction would always consider a stack based on the ability you directly set on the hotbar. regardless of anything that changed it.

You may want to swap to UnknownX7's plugin ReAction as if MOA is broken with combo, it would be on MOA's side.

**Comment by Grammernatzi** [comment]
I do not know anything about delvui, as I do not use it, but I do not have any problems with unknownx7's reaction. Besides, the way this mod replaces actions is the same way it works in the base plugin, so if there are issues, it is on their end.

**Comment by Clickeddaisy** [comment]
I tried ReAction and that worked for mouseover, Thanks. Weird that Delvui or Mouseover Action plugin does not work, at least for me.

**Comment by Grammernatzi** [comment]
Well, for now, it's something that'd have to be fixed on their end. There's not much I can do about it, sadly.
