### ISSUE TITLE
Feature request: Draw feature for AST

### ISSUE THREAD

**Issue by excalibert** [Grammernatzi/XIVComboPluginExpandedest#64]
Any means of preventing hitting draw while a card is already drawn? I prefer draw and play separate, but hate it when I hit draw in my opener when I already had a card drawn. I realize in advance that the solution is "just don't do that", but I want to believe I'm not alone in this.

**Comment by Grammernatzi** [comment]
I could probably just have it turn into malefic or something. I will give it a look later.

**Comment by Grammernatzi** [comment]
Added.
