### ISSUE TITLE
RE: New Monk Combos Discussion

### ISSUE THREAD

**Issue by jjgitprojects** [Grammernatzi/XIVComboPluginExpandedest#65]
This is a repost which was orginally posted under the now-closed issue of "New Monk Combos Discussion', just in case the following suggestion/issue doesn't get raised to you.
------------------------------------

Hi Dev sir, I have a suggestion/issue to raise with regards to one particular detail about the experimental monk combo options.

I appreciate the option that leaves Form Shift alone, instead of turning it into Snap Punch.
In the same line of thinking, I was wondering if there can be an option to leave Perfect Balance alone instead of turning it into Demolish when under the effect of Formless Fist (effect of either using Form Shift or Masterful Blitz).

-----------------------------------------------------------

This option will enable a player to execute (or even weave) another Perfect Balance right after executing Masterful Blitz, because otherwise without this feature, even if there are remaining charges on Perfect Balance, it can NEVER be used IMMEDIATELY until the subsequent Demolish (or any subsequent GCD) is used, hence preventing back-to-back usages of Perfect Balance (i.e needing to spend at least 1 GCD in order to get back the Perfect Balance button) chains.

I am a MNK player myself so I understand that for the most optimal DPS rotation, there is an optimal window to use Perfect Balance in such a way that you should not chain 2 Perfect Balance chains immediately after each other. However, this is mostly true only for encounters that last longer than 2 Perfect Balance-to-Masterful Blitz chains, such as Boss fight rotations. There are practical situations, such as in big AoE situations (big trash pulls in dungeon etc.) when you just want to deal the most burst AoE damage in a short window, which is very often in duties such as dungeons. Hence, having the option to leave Perfect Balance alone (aside from being converted to Masterful Blitz when in possession of 3 beast chakras) could be quite a practical benefit for most players.

Ultimately yes, we are only saving 1 GCD worth of time which some could argue is not worth losing the functionality of Perfect Balance turning into Demolish, which I will acknowledge is useful ONLY IF you end up in the very specific situation that you need to refresh the Demolish DOT (WITHOUT needing to refresh the Twin Snakes/Disciplined Fist buff) either immediately after PB/Masterful Blitz or even right after using Form Shift. But hence, my personal opinion is that it is not meant to be a common situation you find yourself in (e.g. you did not use PB in the "optimal DPS" window of your rotation, which should follow the Opo-opo GDC IMMEDIATELY after refreshing both the Discipline Fist buff and Demolish DOT successively), such that I would just keybind a stand-alone Demolish separately to take into account this particular situation should it ever happen. I feel that an optimal MNK player would find himself with a greater need to execute back-to-back PBs instead of losing the ability to do so, for just 1 particular non-optimal situation. In fact, just having this as an checkable option will give players the flexibility to decide if they want the PB->Demolish under Formless Fist feature or not.

----------------------------------------

Feel free to consider this suggestion in your own capacity and judgement! I very much appreciate the work you for the MNK combos regardless!

**Comment by Grammernatzi** [comment]
I feel maybe a better option would be to have it not turn into demolish if you have no target? Then you could just press escape and boom, you can use PB again. Perfect for AoE.

**Comment by jjgitprojects** [comment]
> I feel maybe a better option would be to have it not turn into demolish if you have no target? Then you could just press escape/circle and boom, you can use PB again. Perfect for AoE, and even for the rare single-target moments you want to do that.

That actually sounds like a good workaround in order to chain back-to-back PBs, and to be sure, if that's what you want to implement instead, I think I would be comfortable with it as well!

It's just that I am a player who is very used to having a target selected EVEN for generic AOE situations, simply because I am used to playing classes that have conal AoEs instead of circular AoEs like WAR, SAM, MCH etc. in which selecting your target is very important in aiming your AoEs. So it will still take a bit to get used to cancelling the target just to chain PB.

But if you have reasons not to add an additional option (perhaps due to clutter especially) for the flexibility to leave PB alone in Formless Fist, then by all means I will respect your decision and work with the workaround you suggested.

**Comment by Grammernatzi** [comment]
I prefer the ability to be able to do both, not having to continuously check/uncheck it. I like having options available at that moment, rather than continuously having to check a box. And while I do get that it might feel awkward, I feel it's better than being locked out of an option altogether; something I could do instead is replace another button with demolish instead.

**Comment by jjgitprojects** [comment]
> I prefer the ability to be able to do both, not having to continuously check/uncheck it. I like having options available at that moment, rather than continuously having to check a box. And while I do get that it might feel awkward, I feel it's better than being locked out of an option altogether; something I could do instead is replace another button with demolish instead.
> 
> I could also add a GCD check like I've been doing for some certain moves, but that would require you being fast enough to press it before the GCD gets into clipping range (if you were too slow, you'd have to untarget). Up to you on that one.

I'd actually like the idea of the GCD check option! That is because if I am seriously considering chaining 2 PB usages, I would optimally want to use it in either the first or second weave window (MNK literally only has Forbidden Chakra/Enlightenment as damaging oGCDs anyway, so there should always be a window for PB weaving in the situations you need to do so), rather then delaying it to the next GCD after Masterful Blitz. That's pretty genius for a suggestion and I would love to work with that!

**Comment by Grammernatzi** [comment]
I already tested it, and it seems to work fine. So I'll just go ahead and push it, then; if that works, then, is good!

**Comment by jjgitprojects** [comment]
just tested it, and weaved my PB after Masterful Blitz perfectly fine! Thank you for your brilliant suggestion, fast work and response Dev sir!
