### ISSUE TITLE
Few tweaks for SAM and RPR

### ISSUE THREAD

**Issue by dvdio** [Grammernatzi/XIVComboPluginExpandedest#66]
For SAM: 
**Iaijutsu to Shoha** / **Tsubame-gaeshi to Shoha** : Shoha should have priority over Kaeshi (because of the burst phase).

**Ikishoten Namikiri Feature** : Before Ogi Namikiri, there should be Hissatsu: Kaiten, since its buffed by it, also Shoha should have priority over any of the combo pieces, 

For RPR:
It would be great to have either a v1 or v2 of the **Gibbets and Gallows Feature**
Now: Slice->Gibbet & Shadow->Gallow
V1: Slice->Gallow & Shadow->Gibbet
V2: Slice->Gallow & Soul Slice->GIbbet

Thk for the work, and happy new year!

**Comment by Grammernatzi** [comment]
Shoha I'll make have priority again but probably add a GCD check. Kaiten I figured you'd just use the normal button for that.

Also, for reaper, I prefer it how it is at the moment, but I'll add a swap option as well as an option that replaces soul slice instead of shadow of death.

**Comment by Grammernatzi** [comment]
I added all of these except Ikishoten into Kaiten, I guess it just seems how much you really want that one. I'll close this but if you really want that I can add it.

**Comment by dvdio** [comment]
Thanks! 
I understand the shoha gcd clip problem, but as a separate option its possible to stay no matter the clip? because for lag, if after there is **Kaeshi: Higanbana**, there is too much of a risk to press that instead (and i ask myself why kaeshi: higanbana still exist).

The ikishoten into kaiten isn't necessary, i thought i could play without binding kaiten, since its a bad design for a button to be pressed only and always before something else specific, without decision making or reactive gameplay, when they could have just added the 20 kenki cost with the same effect added to iaijutsu.. but that's another topic

**Comment by Grammernatzi** [comment]
I do have the Iaijutsu to Kaiten thing, which does help with that, at least. I'm setting it up to affect Ogi-Namikiri as well. I'll also go ahead and add that option. Sadly I can't test the Ogi-Namikiri parts because I don't have SAM 90.
