### ISSUE TITLE
[MCH]: Suggestion for Gauss Round/Ricochet Feature

### ISSUE THREAD

**Issue by jjgitprojects** [Grammernatzi/XIVComboPluginExpandedest#67]
Hi Dev sir,

I would like to suggest adding an option that includes the current **Gauss Round/Ricochet feature to only work under the effect of Hypercharge.** 

--------------------------------

This will optimally use up Gauss Round/Ricochet charges in order to prevent overcapping during Hypercharge windows, but also maintain the ability to independently select usage of Gauss Round and Ricochet in situations outside of Hypercharge. For e.g, during dungeon runs or even boss fights with add mechanics, I might want to intentionally save Ricochet charges for big groups of mobs instead of using them on single trash mobs/boss

---------------------------------

As usual, feel free to consider this suggestion within your own judgement and capacity. Appreciate the impressive response you give to this plugin.

**Comment by Grammernatzi** [comment]
Eh, sure, why not. I'll add it in a second.

**Comment by jjgitprojects** [comment]
Thank you again for the help dev sir!
