### ISSUE TITLE
Trouble with Charge Cooldowns IE Gauss Round and Perfect Balance

### ISSUE THREAD

**Issue by vitharr137** [Grammernatzi/XIVComboPluginExpandedest#68]
Hello!

I'm unsure if this is a XIVCombo, or a larger scale Dalamud issue, as it appears to track incorrectly on SpellTimers as well, but I have noticed that any spell with Charges does not fire off a second round when using the IsActionOffCooldown call. I've tried using a combination of CooldownElapsed and CooldownRemaining to see if I can force it to double up, but it only works (and halts the combo) if the cooldown is not tracked at all. This leaves it stuck on said move until the full charge stack has been recovered. If there's a better way to move through charged cooldowns, I'll give that a shot, too

Thank you!

**Comment by Grammernatzi** [comment]
You're trying to make your own actions, I assume? Then the main issue would be that charge actions are calculated *really weirdly* in FF14 itself, so it's actually a base game issue. It's something both Daemitus and I have had to wrangle with. You have to just try to use CooldownRemaining with it and fiddle around.

**Comment by Grammernatzi** [comment]
It is worth noting that Daemitus made some big changes with how charged cooldowns are read and apparently things work a lot better; I may try to make a big migration to his new codebase, but it would take a lot of work. Currently I've been more focused on adding features than updating the codebase to be on par, but eventually I'm going to have to do it, especially when 6.1 rears its ugly head.

**Comment by vitharr137** [comment]
Thank you! I'll check on both those suggestions, maybe I can swipe some code for the meantime. Everything else is working like a charm, so when that comes in later I'll likely not have any other worries. 

As an aside, I really don't know how github works in general, but I've overhauled the Monk ST Combo for Nadi detection and buff/debuff management using a few tools I found in other forks. Feel free to take anything you want to from this one. It's not 100%, the rotation still halts when PB doesn't trigger (hence the ticket)
[MNK - Copy.txt](https://github.com/Grammernatzi/XIVComboPluginExpandedest/files/7817132/MNK.-.Copy.txt)

**Comment by Grammernatzi** [comment]
Sadly it does too much automatic stuff involving auto-upkeep and the like for me to be comfortable with for putting it in the plugin. Obviously you can use it for your own use, though. Also, I'll go ahead and close this for now, so it doesn't clog up the active issues. I'll likely get the code base updated eventually once things get less active and I have more free time to do so.
