### ISSUE TITLE
Suggestion: Huraijin / Fleeting Raiju Feature.

### ISSUE THREAD

**Issue by RandomSuggestions** [Grammernatzi/XIVComboPluginExpandedest#69]
In 6.05, SE changed how Forked and Fleeting Raiju worked. They're no longer a combo; instead, they're an either/or option that deal the same damage with one big difference between them. Forked Raiju is a gap closer which has the lunge and the short animation lock tied to it that can make positioning for mechanics messy. Fleeting Raiju meanwhile is effectively just a normal weaponskill with no such animation lock to deal with.

In the current version of Expandest, Huraijin / Forked Raiju is the only option. Could we please get a Huraijin/Fleeting Raiju feature so that players can choose which behavior they get after they get their Raiju Ready buff?

**Comment by jjgitprojects** [comment]
Just wanted to chime in with another suggestion for Forked/Fleeting Raiju, don't think its worth raising a new issue for it so tagging it here.

What about an option to replace Fleeting Raiju (the non-gap closer) with Forked Raiju based on distance away from target, i.e Forked Raiju when out of melee range, Fleeting Raiju when in melee range. Is coding based on distance practical?

**Comment by Grammernatzi** [comment]
I figured that Aeolian Edge/Armor Crush being Fleeting/Forked respectively would fix it (since you lose Raiju Ready if you use a GCD), but fair. Especially if you don't use those combos. As for distances, I probably could do that. There's a command to see the distance you are from an enemy.

**Comment by Grammernatzi** [comment]
Both features added.

**Comment by jjgitprojects** [comment]
thank you, impressive as always! will check out the changes especially the distance based one!

**Comment by RandomSuggestions** [comment]
Aw yeah, the Fleeting Raiju feature feels so good. Thanks a ton. 

And yeah, I don't use a lot of the Combo Features outside of the AOE ones. I like to use Combo Expandest as a way to make the game feel closer to my old World of Warcraft bindings where my cooldowns, your Single Target (And occasionally your AOE), and your utility buttons fit into five button clusters. In FF14, that means single target buttons usually stay intact, with either a fifth conditional ST button (Huraijin/Fleeting) or my AOE combo (I.E. GNB's Demon Slaughter) ends up fitting into the 5 slot.

**Comment by Grammernatzi** [comment]
Ah, yeah, fair; I came from GW2, where auto combos are the norm, as well as actions replacing other actions (a necessity caused by the limited hotbar, which, IMO, is a blessing in disguise). FF14's hotbars always felt super bloated in comparison, and that's been especially notable with my friends who have physical disabilities.
