### ISSUE TITLE
Kaiten replacing Kaeshi: Namikiri with Iaijutsu to Kaiten + no clip option

### ISSUE THREAD

**Issue by morodrim** [Grammernatzi/XIVComboPluginExpandedest#70]
Kaiten rightfully replaces Oga Namikiri, but it's also replacing Kaeshi: Namikiri which doesn't benefit from Kaiten.

**Comment by Grammernatzi** [comment]
I think I spotted the problem and fixed it, but I can't test it in-game at the moment.
