### ISSUE TITLE
Fisher stuff maybe?

### ISSUE THREAD

**Issue by Megasder** [Grammernatzi/XIVComboPluginExpandedest#71]
I know this is more combat oriented plugin, but I think fisher can benefit from this plugin and moaction or reaction doesnt let you stack fisher skills. miner or botanist don't benefit.

**_Cast --> Hook (Remove 1 hotkey)_**
While you are fishing you can't throw the line again, so instead of using 2 hotkeys use the same to hook the fish.

**_Cast --> Gig (Remove 1 hotkey)_**
To spearfishing you need to use Gig skill, and you can't use Cast or Hook or any normal fishing skills, so change Cast to Gig.

(Idk if the 2 next ones are even posible, but just asking in case)
**_Mooch II --> Mooch (Remove 1 hotkey)_**
They work the same but Mooch can only be used with some large fish but cost nothing and Mooch II can be used with normal fish but costs 100 gp, so change Mooch II to Mooch only when you can use Mooch, if not use Mooch II

**_Hook --> Precision Hookset
Hook --> Powerful Hookset (Remove 2 hotkey)_**
They can only be used while you are in the patience Buff, when a fish caughts your fishing rod a icon appear above your head, "!" for Weak Bite (So use Precision) and "!!" for Strong Bite (So use Powerful).

So my question is if its posible to detect if its a strong or weak bite and change hook to the skill that needs to be used to catch the fish.

### Change some Skills that can only be used while Spearfishin into skills that can only be used while fishing so it removes some hotkeys, if there are no skill that have the exact effects, just use some skills that have similar effects:

**_Veteran Trade --> Surface slap (Remove 1 hotkey)_**
The 2 skills have the same effect, but 1 is for spearfishing and 2 is for normal fishing

**_Prize Catch  --> Nature's Bounty (Remove 1 hotkey)_**
Same as above

**_Baited Breath --> Chum (Remove 1 hotkey)_**
This time the effects are not the same, but Chum can only be used while normal fishing and Baithed Breath only in spearfishing

**_Electric Current  --> Double Hook (Remove 1 hotkey)_**
Same as above

**Comment by Grammernatzi** [comment]
I will give it a look in the future, cast to hook is a thing I've heard suggested before (though, personally, I already just use a macro for this). I'm not sure if it'd be possible to detect if you're underwater or not. I'd consider this overall low priority though because unlike combat, macro queueing isn't a problem for gatherers.

**Comment by Megasder** [comment]
LOL I was so focused on plugins that I forgot that macros exist XD I will look into that too

**Comment by Grammernatzi** [comment]
I may look at it more in the future, but atm, will close for now.
