### ISSUE TITLE
blm trouble

### ISSUE THREAD

**Issue by Hikarichan** [Grammernatzi/XIVComboPluginExpandedest#73]
so i was messing around on blm and noticed the fire 1 > 3 option
this is super nice but it has one drawback and i dunno if this was just an oversight or something so figured id ask

when u do bliz 3 > bliz 4 > fire 3 this procs Paradox on fire 1 by base game 
now when you swap back out of fire with bliz 3 it also procs paradox on fire 1 but with the swap it wont show up as it changes fire 1 to 3 when out of fire and paradox is procced when switching out of each astral. 

I dont know if there is a way to also incorperate paradox into the fire 1> 3 swap as well but just figured id bring this up as there was no swap for paradox

**Comment by Grammernatzi** [comment]
Shouldn't the Blizzard 3/Blizzard 1 option remedy this? Anyway, I can probably make it so that both Blizz 3/Fire 3 become Paradox if you have either option enabled, since you shouldn't be switching until you've used it anyway.

**Comment by Hikarichan** [comment]
hmm it could. i just nvr even bothered with that option because at 90 there really was no need to put bliz 1 on the bar because you are able to do bliz 3 with no mp as long as astral fire was up. but if you did it that way it would be dummy proof at that point and prolly better.

Thanks for the quick response <3

**Comment by Grammernatzi** [comment]
No prob; I can change it in the future, though, so that Paradox takes priority over Fire 3. For now, will close.
