### ISSUE TITLE
Petition to re-add the BLM Transpose to Umbral Soul option

### ISSUE THREAD

**Issue by KazDvs** [Grammernatzi/XIVComboPluginExpandedest#77]
I know you state you removed this combo due to the potential use of Transpose in the lvl 90 rotation however, I believe that Transposes uses is VERY niche and would only be used by the most min-maxing of players.

Based on the theorycrafting from the Balance Discord here:

https://docs.google.com/document/d/11ZY8zAoz9T8doy8Z_D_UXGiReCp7LMl-HsLlHjYhng8/edit#heading=h.41c70ddtm0qt

Transpose will only be used to any effect if you have a firestarter proc available and its only a very marginal gain to use at all. I feel that for a majority of players this method will not be used and the documentation mentions this. On the flip side I found the transpose to umbral soul combo very useful intuitive and would not hamper the DPS or cause improper play as the expected behavior is still to use a fire 3 to go from umbral ice to astral fire in most situations.

I definitely understand your desire to not have combos that encourage bad play or make it impossible to play your class optimally but I think in this situation it does not apply and thus would like to petition to have it re-added as an option or even a secret combo if you prefer.

**Comment by Grammernatzi** [comment]
What I might do is find some other way to add Umbral Soul in, instead. I'm thinking of just having it replace Blizzard 3 if you don't have a target. That way it wouldn't conflict at all.

**Comment by Grammernatzi** [comment]
I went ahead and added the new feature. Tell me what you think of it after trying it out, and if it works enough as a decent replacement.

**Comment by KazDvs** [comment]
Initial impression is it feels pretty good. Thanks for the quick response always happy to save a button.
