### ISSUE TITLE
Ninja: "GCDs to ninjutsu" being trigger by Kassatsu. Incompatible with opener.

### ISSUE THREAD

**Issue by ProfessorBAG** [Grammernatzi/XIVComboPluginExpandedest#9]
This makes it so you can't use your 123 while holding your Kassatsu which is needed for the opener.
Here is a screenshot for the opener.

![Screenshot(31)](https://user-images.githubusercontent.com/90366279/132612684-ecc7aac2-4d43-44a0-9194-207652d65578.png)

Notice Kassatsu is used early and held for a bit while continuing with the 123 GCD combo and isn't used until about 10 seconds later.
With this features it is not possible to do this since your 123 turns into the ninjutsu button while there is no ninjutsus to use until you start your mudras again.

A solution to this would be to not trigger this when Kassatsu is used and only when the Mudra signs are being pressed if possible.

If that is fixed then this would be the perfect setup for ninja!

On a side note, thank you so much for making this plugin. It has made playable this game much more fun for me not having to worry about so many keybindings that don't feel ergonomic!

**Comment by Grammernatzi** [comment]
Hi, I wasn't aware of this issue and I wasn't getting emailed github issues for some reason. I have to fix the plugin to work with the new Dalamud anyway, so I will look into this.
